In [1]:
import pandas as pd

df = pd.read_csv('data/2016/16relation.csv')
pd.set_option('display.max_columns', 50); 
pd.set_option('display.width', 1000) #将结果完整输出
#显示所有行，把列显示设置成最大
# pd.set_option('display.max_rows', None)
# df.describe().T

/Users/askuy/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (20,40,59,78,97,116,135,154) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [2]:
col_n = ['pid','fid16','tb1y_a_s','tb1m_a_s','tb1y_a_m','code_a_f','pid_f','tb1y_a_f','code_a_m','pid_m','tb4_a16_m','tb4_a16_f','tb4_a16_s','hukou_a16_s','hukou_a16_f','hukou_a16_m','pid_s']
df = pd.DataFrame(df,columns = col_n)
df.describe().T

               count          mean           std          min          25%          50%          75%           max
pid          58179.0  3.932863e+08  1.618040e+08  100051501.0  310275103.5  411021105.0  510399302.5  2.845313e+09
fid16        58179.0  3.849195e+05  1.751831e+05     100051.0     230189.0     410622.0     510324.0  2.845312e+06
tb1y_a_s     57831.0  1.145813e+03  9.737674e+02         -9.0         -8.0       1950.0       1971.0  2.013000e+03
tb1m_a_s     57702.0  3.134727e-01  7.643485e+00         -9.0         -8.0          2.0          7.0  1.200000e+01
tb1y_a_m     58177.0  1.349455e+03  9.093938e+02         -9.0         -8.0       1945.0       1968.0  2.014000e+03
code_a_f     58179.0  1.463254e+02  1.029769e+02         -8.0        101.0        103.0        203.0  5.830000e+02
pid_f        58179.0  1.758206e+08  2.263282e+08         -8.0         -8.0         -8.0  410582102.0  2.845313e+09
tb1y_a_f     58176.0  1.302099e+03  9.265452e+02         -9.0         -8.0       1942.0       1967.0  2.010000e+03
code_a_m     58179.0  1.467717e+02  1.123833e+02         -8.0        101.0        104.0        203.0  5.840000e+02
pid_m        58179.0  1.867931e+08  2.285341e+08         -8.0         -8.0         -8.0  411029102.5  2.845313e+09
tb4_a16_m    58130.0 -2.799587e-01  4.209084e+00         -9.0          1.0          1.0          2.0  8.000000e+00
tb4_a16_f    58140.0 -9.134847e-02  4.437781e+00         -9.0          1.0          2.0          3.0  8.000000e+00
tb4_a16_s    57817.0 -1.779684e+00  5.308110e+00         -9.0         -8.0          1.0          3.0  8.000000e+00
hukou_a16_s  57817.0 -2.755037e+00  4.905883e+00         -8.0         -8.0          1.0          1.0  7.900000e+01
hukou_a16_f  58149.0 -2.775164e+00  4.897299e+00         -8.0         -8.0          1.0          1.0  7.900000e+01
hukou_a16_m  58132.0 -2.350822e+00  4.722269e+00         -8.0         -8.0          1.0          1.0  7.900000e+01
pid_s        58179.0  2.276139e+08  2.268157e+08         -8.0         -8.0  210759103.0  411817317.5  2.845313e+09

In [3]:
df.rename(columns={"fid16":"fid","hukou_a16_s":'mate_hukou','tb4_a16_s':'mate_edu','hukou_a16_f':'hukou_parent_f','hukou_a16_m':'hukou_parent_m','tb4_a16_f':'parent_f_edu','tb4_a16_m':'parent_m_edu','pid_s':'mate_pid'},inplace=True)
df.describe().T
def getMageAge(birthYear):
    if birthYear <= 0:
        return birthYear
    else:
        return (2016-birthYear)
df['mate_age'] = df.apply(lambda x: getMageAge(x.tb1y_a_s), axis=1)
df['parent_f_age'] = df.apply(lambda x: getMageAge(x.tb1y_a_f), axis=1)
df['parent_m_age'] = df.apply(lambda x: getMageAge(x.tb1y_a_m), axis=1)
# print(df)

col_n = ['pid','fid','pid_f','hukou_parent_f','parent_f_age','parent_f_edu','pid_m','hukou_parent_m','parent_m_edu','parent_m_age','mate_edu','mate_hukou','mate_age','mate_pid']
df = pd.DataFrame(df,columns = col_n)
df.describe().T

                  count          mean           std          min          25%          50%          75%           max
pid             58179.0  3.932863e+08  1.618040e+08  100051501.0  310275103.5  411021105.0  510399302.5  2.845313e+09
fid             58179.0  3.849195e+05  1.751831e+05     100051.0     230189.0     410622.0     510324.0  2.845312e+06
pid_f           58179.0  1.758206e+08  2.263282e+08         -8.0         -8.0         -8.0  410582102.0  2.845313e+09
hukou_parent_f  58149.0 -2.775164e+00  4.897299e+00         -8.0         -8.0          1.0          1.0  7.900000e+01
parent_f_age    58176.0  3.656375e+01  3.573796e+01         -9.0         -8.0         43.0         64.0  2.000000e+02
parent_f_edu    58140.0 -9.134847e-02  4.437781e+00         -9.0          1.0          2.0          3.0  8.000000e+00
pid_m           58179.0  1.867931e+08  2.285341e+08         -8.0         -8.0         -8.0  411029102.5  2.845313e+09
hukou_parent_m  58132.0 -2.350822e+00  4.722269e+00         -8.0         -8.0          1.0          1.0  7.900000e+01
parent_m_edu    58130.0 -2.799587e-01  4.209084e+00         -9.0          1.0          1.0          2.0  8.000000e+00
parent_m_age    58177.0  3.724590e+01  3.479963e+01         -9.0         -8.0         43.0         65.0  1.970000e+02
mate_edu        57817.0 -1.779684e+00  5.308110e+00         -9.0         -8.0          1.0          3.0  8.000000e+00
mate_hukou      57817.0 -2.755037e+00  4.905883e+00         -8.0         -8.0          1.0          1.0  7.900000e+01
mate_age        57831.0  2.500031e+01  3.017774e+01         -9.0         -8.0         30.0         51.0  1.030000e+02
mate_pid        58179.0  2.276139e+08  2.268157e+08         -8.0         -8.0  210759103.0  411817317.5  2.845313e+09

In [4]:
import pandas as pd

personDf = pd.read_csv('data/2016/2016.csv')

col_n = ['pid','qg12','provcd16','cfps2016edu','cfps_age','urban16','pa301','qea0','qp201','cfps_gender','qi101','qi200','qi2001','qi1011','fid16','qi201_s_1','qi201_s_2','qi201_s_3','qi201_s_4','qi201_s_5','qi301_s_1','qi301_s_2','qi301_s_3','qi301_s_4','qi301_s_5']
personDf = pd.DataFrame(personDf,columns = col_n)

def isRetire(x):
    if x.qi101 == 1 :
        return 1
    elif x.qi200 == 1 :
        return 1     
    elif x.qi2001 == 1 :
        return 1   
    elif x.qi1011 == 1 :
        return 1             
    # 如果都小于0，才能是为无效数据
    elif (x.qi101 < 0) & (x.qi200 < 0) & (x.qi2001 < 0) & (x.qi1011 < 0) :
        return -8
    else:
        return 0
personDf['is_retire'] = personDf.apply(lambda x:isRetire(x), axis=1)

personDf.rename(columns={'fid16':'fid','pa301':'hukou','qg12':'salary','provcd16':'province','cfps2016edu':"edu","cfps_age":"age","qea0":"marry","qp201":"health","urban16":"urban","cfps_gender":"gender"},inplace=True)
personDf.describe().T

col_n = ['pid','salary','province','edu','age','urban','hukou','marry','health','gender','fid','qi301_s_1','qi301_s_2','qi301_s_3','qi301_s_4','qi301_s_5','is_retire']
personDf = pd.DataFrame(personDf,columns = col_n)
personDf.describe().T

/Users/askuy/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (274,289,305) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

             count          mean           std          min           25%          50%          75%           max
pid        36892.0  3.911677e+08  1.540815e+08  100051501.0  3.100914e+08  410941302.0  510415101.5  2.489152e+09
salary     36892.0  5.653874e+03  1.891564e+04         -9.0 -8.000000e+00         -8.0         -8.0  1.200000e+06
province   36892.0  3.888743e+01  1.503843e+01         -9.0  3.100000e+01         41.0         51.0  6.500000e+01
edu        34992.0  2.659922e+00  1.389866e+00          1.0  1.000000e+00          3.0          3.0  8.000000e+00
age        36892.0  4.595706e+01  1.768883e+01         -8.0  3.000000e+01         46.0         60.0  1.040000e+02
urban      36892.0  4.029871e-01  9.811842e-01         -9.0  0.000000e+00          0.0          1.0  1.000000e+00
hukou      33244.0  1.550896e+00  1.495140e+00         -2.0  1.000000e+00          1.0          3.0  7.900000e+01
marry      36892.0  2.085791e+00  9.040533e-01         -2.0  2.000000e+00          2.0          2.0  5.000000e+00
health     36892.0  3.036891e+00  1.240865e+00         -9.0  2.000000e+00          3.0          4.0  5.000000e+00
gender     36892.0  4.956359e-01  5.284536e-01         -8.0  0.000000e+00          0.0          1.0  1.000000e+00
fid        36892.0  3.818258e+05  1.729753e+05     100051.0  2.268132e+05     410418.0     510297.0  2.845312e+06
qi301_s_1  33244.0  2.638636e+01  3.663942e+01         -8.0  2.000000e+00          6.0         78.0  7.800000e+01
qi301_s_2  33244.0 -7.546294e+00  3.649942e+00         -8.0 -8.000000e+00         -8.0         -8.0  7.700000e+01
qi301_s_3  33244.0 -7.916947e+00  1.477032e+00         -8.0 -8.000000e+00         -8.0         -8.0  7.700000e+01
qi301_s_4  33244.0 -7.981591e+00  4.932762e-01         -8.0 -8.000000e+00         -8.0         -8.0  7.000000e+00
qi301_s_5  33244.0 -7.991517e+00  5.486200e-01         -8.0 -8.000000e+00         -8.0         -8.0  7.700000e+01
is_retire  36892.0 -3.515911e+00  4.246497e+00         -8.0 -8.000000e+00          0.0          1.0  1.000000e+00

In [5]:
newDf = pd.merge(df,personDf,on = ['pid','fid'])
newDf.describe().T

                  count          mean           std          min           25%          50%           75%           max
pid             36892.0  3.911677e+08  1.540815e+08  100051501.0  3.100914e+08  410941302.0  5.104151e+08  2.489152e+09
fid             36892.0  3.818258e+05  1.729753e+05     100051.0  2.268132e+05     410418.0  5.102970e+05  2.845312e+06
pid_f           36892.0  1.253638e+08  2.064588e+08         -8.0 -8.000000e+00         -8.0  2.202884e+08  2.489152e+09
hukou_parent_f  36873.0 -3.418463e+00  4.847247e+00         -8.0 -8.000000e+00         -8.0  1.000000e+00  7.900000e+01
parent_f_age    36890.0  3.938699e+01  3.951527e+01         -9.0 -8.000000e+00         51.0  7.200000e+01  1.560000e+02
parent_f_edu    36869.0 -2.763840e-01  4.302233e+00         -9.0  1.000000e+00          1.0  2.000000e+00  8.000000e+00
pid_m           36892.0  1.366310e+08  2.121127e+08         -8.0 -8.000000e+00         -8.0  3.123892e+08  2.845122e+09
hukou_parent_m  36857.0 -2.769379e+00  4.751211e+00         -8.0 -8.000000e+00          1.0  1.000000e+00  7.900000e+01
parent_m_edu    36858.0 -5.269412e-01  4.021707e+00         -9.0  1.000000e+00          1.0  2.000000e+00  8.000000e+00
parent_m_age    36891.0  4.109013e+01  3.822488e+01         -9.0 -8.000000e+00         52.0  7.200000e+01  1.560000e+02
mate_edu        36615.0  6.543766e-02  4.605598e+00         -9.0  1.000000e+00          2.0  3.000000e+00  8.000000e+00
mate_hukou      36616.0 -9.711875e-01  4.419151e+00         -8.0 -8.000000e+00          1.0  1.000000e+00  7.900000e+01
mate_age        36624.0  3.567988e+01  2.751694e+01         -9.0  2.400000e+01         42.0  5.600000e+01  1.030000e+02
mate_pid        36892.0  2.942868e+08  2.140125e+08         -8.0  1.300601e+08  330017101.5  4.411081e+08  2.844272e+09
salary          36892.0  5.653874e+03  1.891564e+04         -9.0 -8.000000e+00         -8.0 -8.000000e+00  1.200000e+06
province        36892.0  3.888743e+01  1.503843e+01         -9.0  3.100000e+01         41.0  5.100000e+01  6.500000e+01
edu             34992.0  2.659922e+00  1.389866e+00          1.0  1.000000e+00          3.0  3.000000e+00  8.000000e+00
age             36892.0  4.595706e+01  1.768883e+01         -8.0  3.000000e+01         46.0  6.000000e+01  1.040000e+02
urban           36892.0  4.029871e-01  9.811842e-01         -9.0  0.000000e+00          0.0  1.000000e+00  1.000000e+00
hukou           33244.0  1.550896e+00  1.495140e+00         -2.0  1.000000e+00          1.0  3.000000e+00  7.900000e+01
marry           36892.0  2.085791e+00  9.040533e-01         -2.0  2.000000e+00          2.0  2.000000e+00  5.000000e+00
health          36892.0  3.036891e+00  1.240865e+00         -9.0  2.000000e+00          3.0  4.000000e+00  5.000000e+00
gender          36892.0  4.956359e-01  5.284536e-01         -8.0  0.000000e+00          0.0  1.000000e+00  1.000000e+00
qi301_s_1       33244.0  2.638636e+01  3.663942e+01         -8.0  2.000000e+00          6.0  7.800000e+01  7.800000e+01
qi301_s_2       33244.0 -7.546294e+00  3.649942e+00         -8.0 -8.000000e+00         -8.0 -8.000000e+00  7.700000e+01
qi301_s_3       33244.0 -7.916947e+00  1.477032e+00         -8.0 -8.000000e+00         -8.0 -8.000000e+00  7.700000e+01
qi301_s_4       33244.0 -7.981591e+00  4.932762e-01         -8.0 -8.000000e+00         -8.0 -8.000000e+00  7.000000e+00
qi301_s_5       33244.0 -7.991517e+00  5.486200e-01         -8.0 -8.000000e+00         -8.0 -8.000000e+00  7.700000e+01
is_retire       36892.0 -3.515911e+00  4.246497e+00         -8.0 -8.000000e+00          0.0  1.000000e+00  1.000000e+00

In [6]:
import pandas as pd

incomeDf = pd.read_csv('data/2016/16family.csv')
col_n = ['fid14','fid16','familysize16','fincome1']
incomeDf = pd.DataFrame(incomeDf,columns = col_n)
# incomeDf.describe().T

incomeDf.rename(columns={'fid16':'fid',"familysize16":'familysize','fincome1':'fincome'},inplace=True)
incomeDf.describe().T

              count           mean            std       min       25%       50%       75%         max
fid14       14019.0  379041.394607  162489.114557  100051.0  230023.0  410206.0  500373.0   2371541.0
fid         14019.0  365670.907768  183842.249314  100051.0  211779.5  370083.0  450204.5   2845312.0
familysize  14019.0       3.651758       1.891136       1.0       2.0       3.0       5.0        19.0
fincome     13982.0   76986.114075  207905.092063       5.0   25705.0   50000.0   82866.0  11387796.0

In [7]:
newDf = pd.merge(newDf,incomeDf,on = ['fid'])
newDf.describe().T

                  count          mean           std          min          25%          50%          75%           max
pid             36213.0  3.909089e+08  1.535530e+08  100051501.0  310025102.0  410926102.0  510425101.0  2.279963e+09
fid             36213.0  3.825234e+05  1.700765e+05     100051.0     230016.0     410456.0     510332.0  2.845312e+06
pid_f           36213.0  1.236035e+08  2.052993e+08         -8.0         -8.0         -8.0  220007101.0  2.489152e+09
hukou_parent_f  36194.0 -3.439410e+00  4.848472e+00         -8.0         -8.0         -8.0          1.0  7.900000e+01
parent_f_age    36212.0  3.934994e+01  3.960068e+01         -9.0         -8.0         51.0         72.0  1.560000e+02
parent_f_edu    36190.0 -2.808787e-01  4.302137e+00         -9.0          1.0          1.0          2.0  8.000000e+00
pid_m           36213.0  1.350745e+08  2.112008e+08         -8.0         -8.0         -8.0  312013104.0  2.845122e+09
hukou_parent_m  36179.0 -2.785207e+00  4.755007e+00         -8.0         -8.0          1.0          1.0  7.900000e+01
parent_m_edu    36179.0 -5.309710e-01  4.021736e+00         -9.0          1.0          1.0          2.0  8.000000e+00
parent_m_age    36213.0  4.109005e+01  3.831702e+01         -9.0         -8.0         52.0         72.0  1.560000e+02
mate_edu        35944.0  8.418651e-02  4.589759e+00         -9.0          1.0          2.0          3.0  8.000000e+00
mate_hukou      35945.0 -9.285575e-01  4.400957e+00         -8.0         -8.0          1.0          1.0  7.900000e+01
mate_age        35952.0  3.586730e+01  2.747804e+01         -9.0         24.0         43.0         57.0  1.030000e+02
mate_pid        36213.0  2.950876e+08  2.129020e+08         -8.0  130096101.0  330063102.0  441134102.0  2.844272e+09
salary          36213.0  5.540988e+03  1.879344e+04         -9.0         -8.0         -8.0         -8.0  1.200000e+06
province        36213.0  3.886331e+01  1.505570e+01         -9.0         31.0         41.0         51.0  6.500000e+01
edu             34406.0  2.655758e+00  1.387875e+00          1.0          1.0          3.0          3.0  8.000000e+00
age             36213.0  4.607641e+01  1.767017e+01         -8.0         30.0         46.0         60.0  1.040000e+02
urban           36213.0  4.029768e-01  9.779458e-01         -9.0          0.0          0.0          1.0  1.000000e+00
hukou           32783.0  1.551749e+00  1.502138e+00         -2.0          1.0          1.0          3.0  7.900000e+01
marry           36213.0  2.087703e+00  9.040676e-01         -2.0          2.0          2.0          2.0  5.000000e+00
health          36213.0  3.043272e+00  1.239662e+00         -9.0          2.0          3.0          4.0  5.000000e+00
gender          36213.0  4.953194e-01  5.270873e-01         -8.0          0.0          0.0          1.0  1.000000e+00
qi301_s_1       32783.0  2.623820e+01  3.659503e+01         -8.0          2.0          6.0         78.0  7.800000e+01
qi301_s_2       32783.0 -7.546777e+00  3.638808e+00         -8.0         -8.0         -8.0         -8.0  7.700000e+01
qi301_s_3       32783.0 -7.919623e+00  1.405420e+00         -8.0         -8.0         -8.0         -8.0  7.700000e+01
qi301_s_4       32783.0 -7.981332e+00  4.967276e-01         -8.0         -8.0         -8.0         -8.0  7.000000e+00
qi301_s_5       32783.0 -7.991398e+00  5.524631e-01         -8.0         -8.0         -8.0         -8.0  7.700000e+01
is_retire       36213.0 -3.487063e+00  4.245540e+00         -8.0         -8.0          0.0          1.0  1.000000e+00
fid14           36213.0  3.904827e+05  1.597322e+05     100051.0     230622.0     410854.0     510461.0  2.371541e+06
familysize      36213.0  4.356502e+00  2.049694e+00          1.0          3.0          4.0          6.0  1.900000e+01
fincome         36146.0  8.215764e+04  2.276298e+05          5.0      30000.0      51946.0      90000.0  1.138780e+07

In [8]:
import pandas as pd

careDf = pd.read_csv('data/2016/2016_family_care.csv')
col_n = ['fid16','wb202']
careDf = pd.DataFrame(careDf,columns = col_n)
careDf.rename(columns={'fid16':'fid','wb202':'care'},inplace=True)
careDf.describe().T

       count           mean            std       min       25%       50%       75%        max
fid   8427.0  396774.005221  181701.664354  100435.0  239974.0  411110.0  510516.0  2844481.0
care  8427.0      10.929275      21.711030      -8.0       2.0       5.0       5.0       77.0

In [9]:
newDf = pd.merge(newDf,careDf,on = ['fid'])
newDf.describe().T

                  count          mean           std          min          25%          50%          75%           max
pid             45263.0  3.992929e+08  1.516247e+08  100051501.0  311875601.5  411295101.0  510522106.0  2.279963e+09
fid             45450.0  3.912587e+05  1.686823e+05     100051.0     231838.5     410949.0     510424.0  2.845312e+06
pid_f           45263.0  1.246648e+08  2.067365e+08         -8.0         -8.0         -8.0  220221102.0  2.489152e+09
hukou_parent_f  45240.0 -3.413727e+00  4.820497e+00         -8.0         -8.0         -8.0          1.0  7.900000e+01
parent_f_age    45262.0  3.894134e+01  3.929500e+01         -9.0         -8.0         52.0         71.0  1.560000e+02
parent_f_edu    45228.0 -3.554435e-01  4.327317e+00         -9.0          1.0          1.0          2.0  8.000000e+00
pid_m           45263.0  1.374904e+08  2.137546e+08         -8.0         -8.0         -8.0  320325602.0  2.845122e+09
hukou_parent_m  45223.0 -2.770471e+00  4.758122e+00         -8.0         -8.0          1.0          1.0  7.900000e+01
parent_m_edu    45223.0 -6.265617e-01  4.053443e+00         -9.0          1.0          1.0          2.0  8.000000e+00
parent_m_age    45263.0  4.059408e+01  3.807907e+01         -9.0         -8.0         52.0         71.0  1.560000e+02
mate_edu        44950.0  2.851390e-01  4.422317e+00         -9.0          1.0          2.0          3.0  8.000000e+00
mate_hukou      44954.0 -7.572630e-01  4.247774e+00         -8.0          1.0          1.0          1.0  7.900000e+01
mate_age        44962.0  3.607257e+01  2.638990e+01         -9.0         26.0         41.0         56.0  1.030000e+02
mate_pid        45263.0  3.107228e+08  2.118172e+08         -8.0  130590602.0  360189102.0  441910101.5  2.844272e+09
salary          45263.0  5.323385e+03  1.869674e+04         -9.0         -8.0         -8.0         -8.0  1.200000e+06
province        45263.0  3.969410e+01  1.487551e+01         -9.0         31.0         41.0         51.0  6.500000e+01
edu             43071.0  2.596062e+00  1.359488e+00          1.0          1.0          3.0          3.0  8.000000e+00
age             45263.0  4.544767e+01  1.733073e+01         -8.0         31.0         45.0         59.0  1.040000e+02
urban           45263.0  3.739257e-01  9.685103e-01         -9.0          0.0          0.0          1.0  1.000000e+00
hukou           40992.0  1.489266e+00  1.431729e+00         -2.0          1.0          1.0          1.0  7.900000e+01
marry           45263.0  2.093962e+00  8.739851e-01         -2.0          2.0          2.0          2.0  5.000000e+00
health          45263.0  3.023109e+00  1.237351e+00         -9.0          2.0          3.0          4.0  5.000000e+00
gender          45263.0  4.908203e-01  5.277827e-01         -8.0          0.0          0.0          1.0  1.000000e+00
qi301_s_1       40992.0  2.737844e+01  3.677474e+01         -8.0          2.0          6.0         78.0  7.800000e+01
qi301_s_2       40992.0 -7.570770e+00  3.591796e+00         -8.0         -8.0         -8.0         -8.0  7.700000e+01
qi301_s_3       40992.0 -7.928376e+00  1.293650e+00         -8.0         -8.0         -8.0         -8.0  7.700000e+01
qi301_s_4       40992.0 -7.982680e+00  4.761057e-01         -8.0         -8.0         -8.0         -8.0  7.000000e+00
qi301_s_5       40992.0 -7.991145e+00  5.204178e-01         -8.0         -8.0         -8.0         -8.0  7.700000e+01
is_retire       45263.0 -3.720213e+00  4.251486e+00         -8.0         -8.0          0.0          0.0  1.000000e+00
fid14           45263.0  3.988359e+05  1.582667e+05     100051.0     310956.0     411186.0     510552.0  2.371541e+06
familysize      45263.0  4.962817e+00  2.488826e+00          1.0          3.0          5.0          6.0  1.900000e+01
fincome         45185.0  8.233249e+04  2.396198e+05          5.0      30000.0      53060.0      91500.0  1.138780e+07
care            26293.0  1.052752e+01  2.121254e+01         -8.0          2.0          5.0          5.0  7.700000e+01

In [10]:
newDf.to_csv('output/2016_all_process.csv')